stages:
  - build
  - test
  - package
  - pages

before_script:
  - echo "Starting CI/CD pipeline for Spring Boot Gym HTML App"
  - java -version
  - mvn -version
  - cd springboot-gym-html-app  # 👈 Make sure to go to the right directory
  - export PROJECT_DIR=$(pwd)   # Save the path for reuse

build:
  stage: build
  script:
    - cd "$PROJECT_DIR"
    - echo "Compiling the project"
    - mvn clean compile
  tags:
    - windows-runner
  only:
    - main

test:
  stage: test
  script:
    - cd "$PROJECT_DIR"
    - echo "Running tests"
    - mvn test
  tags:
    - windows-runner
  only:
    - main

package:
  stage: package
  script:
    - cd "$PROJECT_DIR"
    - echo "Packaging the application"
    - mvn package
  artifacts:
    paths:
      - springboot-gym-html-app/target/*.jar
  tags:
    - windows-runner
  only:
    - main

pages:
  stage: pages
  script:
    - cd "$PROJECT_DIR"
    - echo "Copying static files for GitLab Pages"
    - mkdir ../public
    - xcopy src\main\resources\static ..\public /E /I /Y
  artifacts:
    paths:
      - public
  tags:
    - windows-runner
  only:
    - main
