stages:
  - build
  - test
  - package

variables:
  MAVEN_CLI_OPTS: "-B -DskipTests"

build-job:
  stage: build
  tags:
    - windows
  script:
    - echo "Building Spring Boot App on Windows..."
    - mvn %MAVEN_CLI_OPTS% clean compile

test-job:
  stage: test
  tags:
    - windows
  script:
    - echo "Running Unit Tests..."
    - mvn test

package-job:
  stage: package
  tags:
    - windows
  script:
    - echo "Packaging the Application..."
    - mvn %MAVEN_CLI_OPTS% package
    - echo "JAR file generated in target directory"
