before_script:
  - echo "Starting CI/CD pipeline on Windows for Spring Boot Gym HTML App"
  - java -version
  - mvn -version
  - cd springboot-gym-html-app  # Change to the directory containing pom.xml

build:
  stage: build
  script:
    - cd springboot-gym-html-app  # Make sure you're in the right folder
    - echo "Compiling the project"
    - mvn clean compile
  tags:
    - windows-runner
  only:
    - main

test:
  stage: test
  script:
    - cd springboot-gym-html-app
    - echo "Running tests"
    - mvn test
  tags:
    - windows-runner
  only:
    - main

package:
  stage: package
  script:
    - cd springboot-gym-html-app
    - echo "Packaging the application"
    - mvn package
  artifacts:
    paths:
      - springboot-gym-html-app/target/*.jar
  tags:
    - windows-runner
  only:
    - main

pages:
  stage: pages
  script:
    - cd springboot-gym-html-app
    - echo "Copying static files for GitLab Pages"
    - mkdir ../public
    - xcopy src\main\resources\static ..\public /E /I /Y
  artifacts:
    paths:
      - public
  tags:
    - windows-runner
  only:
    - main
