stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  tags:
    - windows
  script:
    - echo "Building Spring Boot app..."
    - mvn clean package

test-job:
  stage: test
  tags:
    - windows
  script:
    - echo "Running tests..."
    - mvn test

deploy-job:
  stage: deploy
  tags:
    - windows
  script:
    - echo "Starting Spring Boot app on port 9090..."
    - java -jar target/*.jar &
    - Start-Sleep -Seconds 10
    - curl http://localhost:9090/home.html
