stages:
  - build
  - deploy

variables:
  JAVA_HOME: "C:\\Program Files\\Java\\jdk-17"
  PATH: "C:\\Program Files\\Java\\jdk-17\\bin;E:\\apache-maven-3.9.9\\bin;C:\\Program Files\\Git\\cmd;%PATH%"

build_app:
  stage: build
  tags:
    - windows-runner
  script:
    - echo "Checking Maven version..."
    - mvn -version
    - echo "Building Spring Boot application..."
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 5 min

deploy_app:
  stage: deploy
  tags:
    - windows-runner
  script:
  - echo "Attempting to stop existing process on port 9090..."
  - powershell -Command "try { Get-NetTCPConnection -LocalPort 9090 -State Listen | ForEach-Object { Stop-Process -Id $_.OwningProcess -Force } } catch { Write-Host 'No process found on port 9090 — continuing...' }"
  - echo "Starting Spring Boot application..."
  - powershell -Command "Start-Process -FilePath 'java' -ArgumentList '-jar', 'target\\springboot-gym-html-app-gitlab-windows-1.0.0.jar' -WindowStyle Hidden"
  - timeout /t 10
  - echo "Verifying application is up..."
  - powershell -Command "try { $response = Invoke-WebRequest -Uri http://localhost:9090/ -UseBasicParsing -TimeoutSec 10; Write-Host \"App is up. Status: $($response.StatusCode)\" } catch { Write-Host \"App failed to start or is unreachable.\"; exit 1 }"
