concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "windows-runner"
  url = "https://gitlab.com/"
  id = 47748165
  token = "glrtr-M2Xu9F-GR1348941ic8KW8CApN8qdaNsePom"  # Replace with actual valid token
  token_obtained_at = 2025-06-07T00:00:00Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"
  shell = "pwsh"

  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
