stages:
  - build
  - deploy

variables:
  JAVA_HOME: "C:\\Program Files\\Java\\jdk-17"
  PATH: "$JAVA_HOME\\bin;$PATH"

build_app:
  stage: build
  tags:
    - windows-runner
  script:
    - echo "Building Spring Boot application..."
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 hour

deploy_app:
  stage: deploy
  tags:
    - windows
  script:
    - echo "Attempting to stop existing process on port 9090..."
    - powershell -Command "try { Get-NetTCPConnection -LocalPort 9090 -State Listen -ErrorAction Stop | ForEach-Object { Stop-Process -Id $_.OwningProcess -Force } } catch { Write-Host 'No process found on port 9090 — continuing...' }"
    - echo "Starting Spring Boot application..."
    - powershell -Command "Start-Process java -ArgumentList '-jar target\\springboot-gym-html-app-gitlab-windows-1.0.0.jar' -WindowStyle Hidden"
    - Start-Sleep -Seconds 10
    - echo "Verifying application is up..."
    - curl http://localhost:9090/
