stages:
  - build
  - run
  - test

variables:
  MAVEN_HOME: "E:\\apache-maven-3.9.9"
  JAVA_HOME: "C:\\Program Files\\Java\\jdk-17"
  PATH: "$JAVA_HOME\\bin;$MAVEN_HOME\\bin;$PATH"

build_job:
  stage: build
  tags:
    - windows
  script:
    - echo "Building Spring Boot project..."
    - '%MAVEN_HOME%\\bin\\mvn.cmd clean package -DskipTests'
  artifacts:
    paths:
      - target/*.jar

run_job:
  stage: run
  tags:
    - windows
  script:
    - echo "Starting the Spring Boot app..."
    - powershell -Command "Start-Process -NoNewWindow java -ArgumentList '-jar target/springboot-gym-html-app-gitlab-windows-1.0.0.jar'"
    - timeout /t 10 /nobreak

test_job:
  stage: test
  tags:
    - windows
  script:
    - echo "Checking if app is running..."
    - curl http://localhost:9090/Home.html
